# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
