# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20161220_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentaggregate',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='document',
            name='address',
        ),
        migrations.RemoveField(
            model_name='document',
            name='city',
        ),
        migrations.RemoveField(
            model_name='document',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='position',
        ),
        migrations.RemoveField(
            model_name='document',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='state',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='document_ptr',
        ),
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='documents', to='archive.DocumentCatergory'),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='archive.StorageLocation'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='archive.Tag'),
        ),
        migrations.AlterField(
            model_name='documentcatergory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='archive.DocumentCatergory'),
        ),
        migrations.DeleteModel(
            name='DocumentAggregate',
        ),
        migrations.AddField(
            model_name='documentpart',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='archive.Document'),
        ),
        migrations.AddField(
            model_name='documentpart',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='archive.DocumentType'),
        ),
        migrations.AddField(
            model_name='photo',
            name='documentpart_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.DocumentPart'),
            preserve_default=False,
        ),
    ]
